"""vault_safe_paths -- Blocklist of paths that LLMs must never write to.

Pattern origin: JuliusBrussee/caveman (caveman-compress/scripts/detect.py),
MIT-licensed, 2026-04. Caveman uses a file-extension blocklist to refuse
compressing code/config files. We extend the same idea to vault writes:
some directories and extensions are off-limits to LLM-driven writes
regardless of the request, because corrupting them silently breaks
Obsidian, git, or the local plugin runtime.

Three layers of defense
-----------------------
  1. EXTENSION BLOCKLIST -- inherited from caveman, plus vault additions.
     Anything with these extensions cannot be written by an LLM.
  2. DIRECTORY BLOCKLIST -- vault-specific. .obsidian/, .git/, .trash/
     etc. The plugin owns these; LLM writes here corrupt config or
     destroy version history.
  3. PATH-TRAVERSAL CHECK -- blocks .., ., absolute paths, drive letters.
     Defense-in-depth; the WebSocket handler should reject these too.

Usage
-----
    from vault_safe_paths import is_safe_to_write

    if not is_safe_to_write(path):
        raise PermissionError(f"refusing LLM write to protected path: {path}")
    # ... proceed with write
"""

from __future__ import annotations

from pathlib import PurePosixPath

__all__ = [
    "BLOCKED_EXTENSIONS",
    "BLOCKED_DIRECTORIES",
    "ALLOWED_VAULT_EXTENSIONS",
    "is_safe_to_write",
    "is_blocked_extension",
    "is_blocked_directory",
]


# ---------- Caveman-inherited extension blocklist ----------
# Source: caveman-compress/scripts/detect.py SKIP_EXTENSIONS
# These are code/config files. Caveman skips them for compression;
# we refuse to LLM-write them in the vault.

_CAVEMAN_SKIP_EXTENSIONS: frozenset[str] = frozenset({
    ".py", ".js", ".ts", ".tsx", ".jsx",
    ".json", ".yaml", ".yml", ".toml",
    ".env", ".lock",
    ".css", ".scss", ".html", ".xml",
    ".sql", ".sh", ".bash", ".zsh",
    ".go", ".rs", ".java",
    ".c", ".cpp", ".h", ".hpp",
    ".rb", ".php", ".swift", ".kt", ".lua",
    ".dockerfile", ".makefile",
    ".csv", ".ini", ".cfg",
})

# ---------- Vault-specific extension additions ----------
# Binary, executable, and credential extensions that should never be
# generated by an LLM at all, even if the path is in the vault.

_VAULT_EXTRA_BLOCKED: frozenset[str] = frozenset({
    # Binaries / executables
    ".exe", ".dll", ".so", ".dylib", ".bin",
    # Compressed archives (LLM cannot meaningfully generate these)
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
    # Images (LLM cannot generate raster bytes via text channel)
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".ico", ".svg",
    # Audio / video
    ".mp3", ".mp4", ".wav", ".flac", ".webm", ".mov", ".avi", ".mkv",
    # Documents (binary)
    ".pdf", ".docx", ".xlsx", ".pptx",
    # Credentials / secrets
    ".pem", ".key", ".crt", ".pfx", ".p12", ".gpg", ".asc",
    # Database files
    ".db", ".sqlite", ".sqlite3", ".duckdb",
    # Git internals
    ".pack", ".idx",
})

BLOCKED_EXTENSIONS: frozenset[str] = _CAVEMAN_SKIP_EXTENSIONS | _VAULT_EXTRA_BLOCKED

# Vault is markdown-first. These are the safe extensions LLMs can write.
ALLOWED_VAULT_EXTENSIONS: frozenset[str] = frozenset({
    ".md", ".markdown", ".txt", ".rst",
    # Frontmatter-only files used by some Obsidian plugins.
    ".canvas",  # Obsidian Canvas JSON files -- gated separately, see below
})

# ---------- Directory blocklist ----------
# Path components (anywhere in the path) that mark protected directories.
# Match is exact-segment, not substring.

BLOCKED_DIRECTORIES: frozenset[str] = frozenset({
    # Obsidian config and plugin internals
    ".obsidian",
    ".obsidian.bak",
    # Git internals
    ".git",
    ".gitea",
    ".github",
    # Trash and cache
    ".trash",
    ".cache",
    ".tmp",
    "node_modules",
    "__pycache__",
    # Vault-bridge / vault-mind internals
    ".vault-bridge",
    ".vault-mind",
    # GSD planning (separate workflow, not LLM-writable from vault path)
    ".planning",
    # FSC internals
    ".fsc",
    # Memory keeper persistent state
    ".memory_keeper",
})


# ---------- Checks ----------


def is_blocked_extension(path: str) -> bool:
    """True if the file extension is on the blocklist (Caveman + vault extras)."""
    # TODO(P2): bare dotfiles like ".env" bypass this check because
    # PurePosixPath(".env").suffix == "" -- pathlib treats the leading dot
    # as the stem, not the suffix. So is_safe_to_write(".env") returns True
    # even though ".env" is in _CAVEMAN_SKIP_EXTENSIONS. Fix direction:
    # special-case bare dotfile filenames here, or move ".env" out of the
    # extension blocklist into a filename blocklist. Test
    # `test_dotenv_filename_reaches_blocklist_via_suffix_only` documents
    # the current (broken) behavior.
    suffix = PurePosixPath(path.replace("\\", "/")).suffix.lower()
    if not suffix:
        return False
    return suffix in BLOCKED_EXTENSIONS


def is_blocked_directory(path: str) -> bool:
    """True if any path segment matches a blocked directory."""
    parts = PurePosixPath(path.replace("\\", "/")).parts
    for part in parts:
        if part in BLOCKED_DIRECTORIES:
            return True
    return False


def _normalize_vault_path(path: str) -> str:
    """Normalize a vault-relative path to match the TypeScript handler.

    The TS handler at src/handlers.ts:19-22 strips leading ``./``, collapses
    consecutive ``/`` separators, and drops bare ``.`` segments before
    forwarding the path to the safety gate.  This function replicates that
    normalization so both layers agree on borderline paths.

    Absolute paths and ``..`` segments are left intact so that the caller
    (``_has_path_traversal``) can still detect and reject them.
    """
    norm = path.replace("\\", "/")
    # Strip a single leading "./" (sloppy LLM clients often emit these).
    if norm.startswith("./"):
        norm = norm[2:]
    # Collapse consecutive slashes.
    while "//" in norm:
        norm = norm.replace("//", "/")
    # Drop bare "." segments that appear anywhere in the path (e.g. "a/./b").
    # We keep ".." so that _has_path_traversal can still reject it.
    parts = norm.split("/")
    parts = [p for p in parts if p != "."]
    norm = "/".join(parts)
    return norm


def _has_path_traversal(path: str) -> bool:
    """True if the path contains traversal markers or absolute prefixes."""
    # Normalize first so that "." segments are stripped before checking.
    norm = _normalize_vault_path(path)
    if norm.startswith("/"):
        return True
    # Windows drive letter (C:, D:, ...).
    if len(norm) >= 2 and norm[1] == ":":
        return True
    parts = norm.split("/")
    return any(p == ".." for p in parts)


def is_safe_to_write(path: str, *, allow_canvas: bool = False) -> bool:
    """Decide if an LLM-driven write to this path is safe.

    Args:
        path: The relative vault path. Forward or back slashes accepted.
        allow_canvas: If True, .canvas files are allowed. Default False
            because Obsidian Canvas JSON is binary-fragile and one bad
            write can corrupt the entire canvas. Enable only if you
            have a Canvas-aware writer.

    Returns:
        True iff the path is safe for LLM-driven write. False otherwise.

    Examples:
        is_safe_to_write("notes/idea.md")        -> True
        is_safe_to_write(".obsidian/config.json") -> False  (blocked dir)
        is_safe_to_write("scripts/run.py")       -> False  (blocked ext)
        is_safe_to_write("../secrets.md")        -> False  (traversal)
        is_safe_to_write("notes/draft.canvas")   -> False  (canvas gated)
    """
    if not path or not path.strip():
        return False
    # Normalize first so that "." segments and leading "./" are stripped
    # before any check runs.  _has_path_traversal also calls
    # _normalize_vault_path internally; we normalize here so the directory
    # and extension checks also see the cleaned path.
    normalized = _normalize_vault_path(path)
    if _has_path_traversal(path):
        return False
    if is_blocked_directory(normalized):
        return False
    if is_blocked_extension(normalized):
        return False
    suffix = PurePosixPath(normalized).suffix.lower()
    if suffix == ".canvas" and not allow_canvas:
        return False
    # TODO(P3): the `if suffix` prefix lets extensionless files
    # (Makefile, README, dotfiles like ".env" -- see is_blocked_extension
    # P2) fall through and return True. The stated intent of this module
    # is markdown-first, so unknown OR missing suffixes should both be
    # refused. Fix direction: drop the `if suffix` prefix, or add an
    # explicit extensionless branch. Test `test_extensionless_file_refused`
    # documents the current (broken) behavior.
    if suffix and suffix not in ALLOWED_VAULT_EXTENSIONS:
        # Unknown extension -- err on the side of safety.
        return False
    return True
